### ISSUE TITLE
Pijltjes op pseudo-element

### ISSUE THREAD

**Issue by MicheleNL** [heleensnoeck/css-to-the-rescue#1]
Niet fout, maar kijk nog even of je die pijltjes in je pseudo-element :after toch werkend kunt krijgen. Wanneer je deze techniek beheerst kun je heel veel leuke dingen met pseudo-elementen doen.

**Comment by heleensnoeck** [comment]
ul li a:after {
    content: "";
    width: 25px;
    height: 34px;
    background: transparent url('../images/arrow.svg') no-repeat;
    display: inline-block;
    color: #ffffff;
    vertical-align: -13px;
    margin-left: 0.5em;
}

opgelost :) bedankt voor je feedback
