### ISSUE TITLE
Fallback voor je toffe gradients

### ISSUE THREAD

**Issue by MicheleNL** [heleensnoeck/css-to-the-rescue#2]
Wanneer je in ouderwetse browsers je website bekijkt, zie je je toffe gradients niet meer. Kijk even of je hier een fallback voor kunt specificeren.

**Comment by heleensnoeck** [comment]
Deze fallback heb ik toegevoegd. 

background: purple;
background-image: -webkit-linear-gradient(to right top, #8e44ad 0%, #3498db 100%);
background-image: -o-linear-gradient(to right top, #8e44ad 0%, #3498db 100%);
background-image: -moz-linear-gradient(to right top, #8e44ad 0%, #3498db 100%);
background-image: linear-gradient(to right top, #8e44ad 0%, #3498db 100%);
